#ifndef _COLLISIONFILTERS__H__
#define _COLLISIONFILTERS__H__

//2^x

// Category
int CATEGORY_PLAYER = 0x0001;  
int CATEGORY_WALL = 0x0002; 
int CATEGORY_SCENERY = 0x0004;

// Mask
int MASK_PLAYER = CATEGORY_SCENERY;
int MASK_MONSTER = CATEGORY_PLAYER | CATEGORY_SCENERY;
int MASK_SCENERY = -1;

#endif // !_COLLISIONFILTERS__H__